[#11] 페이지 최상단 커버 추가
wafflestudio/wafflestudio.com-v3 pull request #37
Opened 2022-03-12 10:35 UTC by ars-ki-00

- 페이시 최상단 커버 추가

폰트 head에서 link로 갖고 오고 싶었는데 cors 떠서 ttf 파일 추가
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48665265/158014618-e30bae79-97db-4091-9669-94c500fda953.png">

2022-03-14 02:51 UTC, woohm402 requested changes

2022-03-14 02:51 UTC, woohm402 commented on public/global.css
> +}
.

2022-03-14 04:52 UTC, ars-ki-00 commented on public/global.css
> +}
너무 무성의하네;;;;

2022-03-14 05:16 UTC, woohm402 commented on public/global.css
> +}
프리티어 자동 안써요..?

2022-03-17 12:55 UTC, ars-ki-00 commented on public/global.css
> +}
쓰는데,,,?

2022-03-17 12:58 UTC, woohm402 commented on public/global.css
> +}
근데 왜 안돌았을까요?

2022-03-17 12:58 UTC, woohm402 approved these changes

2022-03-17 16:17 UTC, merged